#!/bin/bash
TMPBG=/tmp/screen.png
RES=$(xrandr | grep 'current' | sed -E 's/.*current\s([0-9]+)\sx\s([0-9]+).*/\1x\2/')

setxkbmap gb
ffmpeg -f x11grab -draw_mouse 0 -video_size $RES -y -i $DISPLAY -filter_complex "boxblur=10:4" -vframes 1 $TMPBG -loglevel quiet
sleep 1
i3lock -i $TMPBG -n; screenon
rm $TMPBG
