#!/bin/sh

setxkbmap us

while true; do
    #Set caps to escape
    setxkbmap -option caps:escape
    #setxkbmap -option esperanto:qwerty

    #Change re-press speed
    xset r rate 300 50
    sleep 10
done
