#!/bin/bash

pkill mpv ; pkill mpv ; pkill mpv

# Generates random track number
# First number is the max to generate
TRACKNO=$((  $RANDOM % 8 + 1 ))

# Play the Jazz
mpv ~/Music/BGM-Jazz/track$TRACKNO\.mp3 --volume=17 --loop --start=$(($RANDOM % 75 + 1))% &
